version: '3'
services:
  machines:
    build:
      context: .
      dockerfile: machine_simulator/dockerfile
    environment:
      - MACHINES=2
      - BROKER=broker.hivemq.com
      - PORT=1883
    ports:
      - 5005:5005
    networks:
      - factory
networks: 
  factory:


