version: '3.6'
services:
  machines:
    build:
      context: .
      dockerfile: machine_simulator/dockerfile
    environment:
      - MACHINES=2
      - BROKER=mosquitto
    networks:
      - factory
    depends_on:
      - "mosquitto"
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    networks:
      - factory
    depends_on:
      - "mosquitto"
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - factory
    volumes: 
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  # task engine:
  anomaly-detection:
    build:
      context: ./task-engine/anomaly-detection
      dockerfile: ./Dockerfile
    environment:
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INTERVAL=300
    restart: always
    networks:
      - factory
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=influxdata-flightsql-datasource
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes: 
      - ./plugins/influxdata-flightsql-datasource:/var/lib/grafana/plugins/influxdata-flightsql-datasource
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - factory
    
networks: 
  factory:
    name: factory

