apiVersion: 1

datasources:
  - name: FlightSQL
    type: influxdata-flightsql-datasource
    typeName: FlightSQL
    access: proxy
    url: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      host: ${INFLUX_HOST}:443
      metadata:
      - bucket-name: ${INFLUX_BUCKET}
      secure: true
      token: ${INFLUX_TOKEN}
    readOnly: false

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: https://${INFLUX_HOST}
    user: user
    jsonData:
      dbName: ${INFLUX_BUCKET}
      httpMode: POST
    secureJsonData:
      password: ${INFLUX_TOKEN}




